#!/usr/bin/env python3
"""
Generate historical board lists from ACTUAL draft-class membership.

Rule (project owner): each class's data universe is exactly the players
ELIGIBLE for that draft — everyone drafted, plus undrafted players whose
final college season was that year (they left school). Players who RETURNED
to college (appear in a later season's data) are not part of that class,
whether or not they later reached the NBA. NBA outcomes never gate
membership.

For each year with draft results this script:
  1. Flags returners in datasets/history/undrafted_results_<year>.json
     ('returned': true) by checking later season files for the same name.
  2. Writes datasets/board_lists/board_<year>.txt:
        picks in draft order, then eligible undrafted by board rank.

The current season's list is user-curated and never touched.

Usage:
    python -m scripts.make_class_boards            # all years with results
    python -m scripts.make_class_boards 2021 2022  # subset
"""

import sys

from core import HISTORY_DIR, SEASON_YEAR, load_json, save_json
from core.config import BOARD_LISTS_DIR, PLAYERS_FILE
from core.names import normalize_name

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8")


def _later_season_names(year: int) -> set:
    """Normalized names appearing in any season AFTER `year` (i.e. returners)."""
    names = set()
    for f in HISTORY_DIR.glob("players_*.json"):
        y = int(f.stem.split("_")[1])
        if y > year:
            names |= {normalize_name(p["name"]) for p in load_json(f)["players"]}
    if SEASON_YEAR > year and PLAYERS_FILE.exists():
        names |= {normalize_name(p["name"]) for p in load_json(PLAYERS_FILE)["players"]}
    return names


def make_year(year: int) -> None:
    df = HISTORY_DIR / f"draft_results_{year}.json"
    if not df.exists():
        print(f"{year}: no draft results — skipped")
        return
    picks = load_json(df)["picks"]
    lines = [f"# Board for the {year} draft class — generated by scripts/make_class_boards.py",
             "# Population: actual draftees (draft order) + eligible undrafted (left college).",
             "# Returners (came back to school) are excluded from this class by rule."]
    for p in sorted(picks, key=lambda r: r["pick_overall"]):
        college = (p.get("college") or "").strip()
        lines.append(f"{p['player']} | {college}" if college else p["player"])

    uf = HISTORY_DIR / f"undrafted_results_{year}.json"
    n_udfa = n_returned = 0
    if uf.exists():
        data = load_json(uf)
        later = _later_season_names(year)
        eligible = []
        for r in data["players"]:
            r["returned"] = normalize_name(r["player"]) in later
            if r["returned"]:
                n_returned += 1
            else:
                eligible.append(r)
        save_json(uf, data)  # persist the flags for the training side
        lines.append("# — eligible undrafted (final college season, never drafted) —")
        for r in sorted(eligible, key=lambda r: r.get("ncaa_rank") or 999):
            lines.append(f"{r['player']} | {r.get('college', '')}")
        n_udfa = len(eligible)

    out = BOARD_LISTS_DIR / f"board_{year}.txt"
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"{year}: {len(picks)} drafted + {n_udfa} eligible undrafted "
          f"({n_returned} returners excluded) -> {out.name}")


def main():
    args = [a for a in sys.argv[1:] if a.isdigit()]
    if args:
        years = [int(a) for a in args]
    else:
        years = sorted(int(f.stem.split("_")[-1])
                       for f in HISTORY_DIR.glob("draft_results_*.json"))
    for y in years:
        make_year(y)


if __name__ == "__main__":
    main()
